language: objective-c
osx_image: xcode10
xcode_scheme:
    - LoopKit
    - LoopKitUI
script:
   - xcodebuild -project LoopKit.xcodeproj -scheme LoopKit build -destination 'name=iPhone XS' test
   - xcodebuild -project LoopKit.xcodeproj -scheme "LoopKit Example" build -destination 'name=iPhone XS'
